2015/04/15 19:34:13 [error] [php] Trying to get property of non-object (E:\PROGRAMY\xampp\htdocs\NET\net\application\protected\views\test\show.php:7)
Stack trace:
#0 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(869): TestController->renderFile()
#1 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(782): TestController->renderPartial()
#2 E:\PROGRAMY\xampp\htdocs\NET\net\application\protected\controllers\TestController.php(22): TestController->render()
#3 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\actions\CInlineAction.php(49): TestController->actionShow()
#4 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(286): TestController->runAction()
#6 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(265): TestController->runActionWithFilters()
#7 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(282): TestController->run()
#8 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 E:\PROGRAMY\xampp\htdocs\NET\net\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php(13): CWebApplication->run()
REQUEST_URI=/test/show
in E:\PROGRAMY\xampp\htdocs\NET\net\application\protected\views\test\show.php (7)
in E:\PROGRAMY\xampp\htdocs\NET\net\application\protected\controllers\TestController.php (22)
in E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php (13)
2015/04/15 19:39:59 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42703]: Undefined column: 7 BŁĄD:  kolumna "Tola" nie istnieje
LINE 1: INSERT INTO users (name,age,city) VALUES ("Tola", 34, "Radom...
                                                  ^. The SQL statement executed was: INSERT INTO users (name,age,city) VALUES ("Tola", 34, "Radom").
in E:\PROGRAMY\xampp\htdocs\NET\net\application\protected\controllers\TestController.php (29)
in E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php (13)
2015/04/15 19:39:59 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42703]: Undefined column: 7 BŁĄD:  kolumna "Tola" nie istnieje
LINE 1: INSERT INTO users (name,age,city) VALUES ("Tola", 34, "Radom...
                                                  ^. The SQL statement executed was: INSERT INTO users (name,age,city) VALUES ("Tola", 34, "Radom")' in E:\PROGRAMY\xampp\htdocs\NET\net\framework\db\CDbCommand.php:358
Stack trace:
#0 E:\PROGRAMY\xampp\htdocs\NET\net\application\protected\controllers\TestController.php(29): CDbCommand->execute()
#1 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\actions\CInlineAction.php(49): TestController->actionAdd()
#2 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(282): CController->run('add')
#6 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(141): CWebApplication->runController('test/add')
#7 E:\PROGRAMY\xampp\htdocs\NET\net\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/test/add
---
2015/04/15 19:41:09 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42703]: Undefined column: 7 BŁĄD:  kolumna "tola" nie istnieje
LINE 1: INSERT INTO users (name,age,city) VALUES (Tola, 34, Radom)
                                                  ^. The SQL statement executed was: INSERT INTO users (name,age,city) VALUES (Tola, 34, Radom).
in E:\PROGRAMY\xampp\htdocs\NET\net\application\protected\controllers\TestController.php (29)
in E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php (13)
2015/04/15 19:41:09 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42703]: Undefined column: 7 BŁĄD:  kolumna "tola" nie istnieje
LINE 1: INSERT INTO users (name,age,city) VALUES (Tola, 34, Radom)
                                                  ^. The SQL statement executed was: INSERT INTO users (name,age,city) VALUES (Tola, 34, Radom)' in E:\PROGRAMY\xampp\htdocs\NET\net\framework\db\CDbCommand.php:358
Stack trace:
#0 E:\PROGRAMY\xampp\htdocs\NET\net\application\protected\controllers\TestController.php(29): CDbCommand->execute()
#1 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\actions\CInlineAction.php(49): TestController->actionAdd()
#2 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(282): CController->run('add')
#6 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(141): CWebApplication->runController('test/add')
#7 E:\PROGRAMY\xampp\htdocs\NET\net\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/test/add
---
2015/04/15 19:41:39 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42703]: Undefined column: 7 BŁĄD:  kolumna "tola" nie istnieje
LINE 1: INSERT INTO users (name,age,city) VALUES (`Tola`, 34, `Radom...
                                                   ^. The SQL statement executed was: INSERT INTO users (name,age,city) VALUES (`Tola`, 34, `Radom`).
in E:\PROGRAMY\xampp\htdocs\NET\net\application\protected\controllers\TestController.php (29)
in E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php (13)
2015/04/15 19:41:39 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42703]: Undefined column: 7 BŁĄD:  kolumna "tola" nie istnieje
LINE 1: INSERT INTO users (name,age,city) VALUES (`Tola`, 34, `Radom...
                                                   ^. The SQL statement executed was: INSERT INTO users (name,age,city) VALUES (`Tola`, 34, `Radom`)' in E:\PROGRAMY\xampp\htdocs\NET\net\framework\db\CDbCommand.php:358
Stack trace:
#0 E:\PROGRAMY\xampp\htdocs\NET\net\application\protected\controllers\TestController.php(29): CDbCommand->execute()
#1 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\actions\CInlineAction.php(49): TestController->actionAdd()
#2 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(282): CController->run('add')
#6 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(141): CWebApplication->runController('test/add')
#7 E:\PROGRAMY\xampp\htdocs\NET\net\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/test/add
---
2015/04/15 19:43:48 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42703]: Undefined column: 7 BŁĄD:  kolumna "Tola" nie istnieje
LINE 1: INSERT INTO users (name,age,city) VALUES ("Tola", 34, "Radom...
                                                  ^. The SQL statement executed was: INSERT INTO users (name,age,city) VALUES ("Tola", 34, "Radom");.
in E:\PROGRAMY\xampp\htdocs\NET\net\application\protected\controllers\TestController.php (29)
in E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php (13)
2015/04/15 19:43:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42703]: Undefined column: 7 BŁĄD:  kolumna "Tola" nie istnieje
LINE 1: INSERT INTO users (name,age,city) VALUES ("Tola", 34, "Radom...
                                                  ^. The SQL statement executed was: INSERT INTO users (name,age,city) VALUES ("Tola", 34, "Radom");' in E:\PROGRAMY\xampp\htdocs\NET\net\framework\db\CDbCommand.php:358
Stack trace:
#0 E:\PROGRAMY\xampp\htdocs\NET\net\application\protected\controllers\TestController.php(29): CDbCommand->execute()
#1 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\actions\CInlineAction.php(49): TestController->actionAdd()
#2 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(282): CController->run('add')
#6 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(141): CWebApplication->runController('test/add')
#7 E:\PROGRAMY\xampp\htdocs\NET\net\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/test/add
---
2015/04/15 21:03:23 [error] [exception.CDbException] exception 'CDbException' with message 'The table "Users" for active record class "Users" cannot be found in the database.' in E:\PROGRAMY\xampp\htdocs\NET\net\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 E:\PROGRAMY\xampp\htdocs\NET\net\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 E:\PROGRAMY\xampp\htdocs\NET\net\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#2 E:\PROGRAMY\xampp\htdocs\NET\net\application\protected\controllers\TestController.php(43): CActiveRecord->__construct()
#3 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\actions\CInlineAction.php(49): TestController->actionAddSecond()
#4 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(282): CController->run('addSecond')
#8 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(141): CWebApplication->runController('test/addSecond')
#9 E:\PROGRAMY\xampp\htdocs\NET\net\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/test/addSecond
---
2015/04/15 21:03:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\PROGRAMY\xampp\htdocs\NET\net\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2015/04/15 21:05:18 [error] [exception.CDbException] exception 'CDbException' with message 'The table "Users" for active record class "Users" cannot be found in the database.' in E:\PROGRAMY\xampp\htdocs\NET\net\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 E:\PROGRAMY\xampp\htdocs\NET\net\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 E:\PROGRAMY\xampp\htdocs\NET\net\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#2 E:\PROGRAMY\xampp\htdocs\NET\net\application\protected\controllers\TestController.php(43): CActiveRecord->__construct()
#3 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\actions\CInlineAction.php(49): TestController->actionAddSecond()
#4 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(282): CController->run('addSecond')
#8 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(141): CWebApplication->runController('test/addSecond')
#9 E:\PROGRAMY\xampp\htdocs\NET\net\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/test/addSecond
---
2015/04/15 21:05:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\PROGRAMY\xampp\htdocs\NET\net\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2015/04/15 21:07:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\PROGRAMY\xampp\htdocs\NET\net\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2015/04/15 21:09:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\PROGRAMY\xampp\htdocs\NET\net\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\PROGRAMY\xampp\htdocs\NET\net\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\PROGRAMY\xampp\htdocs\NET\net\application\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
